default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: YTJ_development
  username: sofia
  password: qwerty

test:
  <<: *default
  database: YTJ_test
  username: sofia
  password: qwerty

production:
  <<: *default
  database: YTJ_production
  username: YTJ
  password: <%= ENV['YTJ_DATABASE_PASSWORD'] %>
